services:
  api:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGUSER=kullanici
      - PGPASSWORD=sifre
      - PGDATABASE=veritabani
      - PGHOST=postgres
      - PGPORT=5432
      - PORT=3000
      - DEBUG=app:*
    mem_limit: 512m
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kullanici
      POSTGRES_PASSWORD: sifre
      POSTGRES_DB: veritabani
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kullanici -d veritabani"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
